# After editing this file please run yamllint on it and fix all violations

site_name: Pipeline - PHP Functional Programming Library
site_description: |
  Comprehensive documentation for the Pipeline PHP library
repo_url: https://github.com/sanmai/pipeline
repo_name: sanmai/pipeline

theme:
  name: readthedocs

nav:
  - Home: index.md
  - Quick Start:
      - Installation: quickstart/installation.md
      - Basic Usage: quickstart/basic-usage.md
      - Examples: quickstart/examples.md
  - Pipeline Cookbook:
      - Overview: cookbook/index.md
      - Associative Arrays: cookbook/associative-arrays.md
      - Testable Pipelines: cookbook/testable-pipelines.md
  - API Reference:
      - Pipeline Creation: api/creation.md
      - Transformation Methods: api/transformation.md
      - Filtering Methods: api/filtering.md
      - Aggregation Methods: api/aggregation.md
      - Collection Methods: api/collection.md
      - Utility Methods: api/utility.md
      - Helper Functions: api/helpers.md
      - Statistics: api/statistics.md
  - Advanced Usage:
      - Complex Pipelines: advanced/complex-pipelines.md
      - Performance Tips: advanced/performance.md
      - Best Practices: advanced/best-practices.md
  - Reference:
      - Method Index: reference/method-index.md
      - Changelog: reference/changelog.md

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true

plugins:
  - search
