# After editing this file please run yamllint on it and fix all violations

site_name: Pipeline - PHP Functional Programming Library
site_description: |
  Comprehensive documentation for the Pipeline PHP library
repo_url: https://github.com/sanmai/pipeline
repo_name: sanmai/pipeline

theme:
  name: readthedocs

nav:
  - Home: index.md

markdown_extensions:
  - admonition
  - def_list
  - footnotes
  - tables
  - toc:
      permalink: true

plugins:
  - search
