# yamllint disable rule:line-length
name: Static Analysis and Validation

on:
  pull_request:
  push:
    branches:
      - v*.*

jobs:
  main:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php-version: ['7.4']

    name: Analyse and Validate on PHP ${{ matrix.php-version }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-version }}
          extensions: ast
          coverage: pcov
          tools: composer:v2

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: ~/.cache/composer
          key: composer-${{ matrix.php-version }}-${{ hashFiles('**/composer.*') }}
          restore-keys: |
            composer-${{ matrix.php-version }}-
            composer-

      - name: Install dependencies
        run: |
          composer update --prefer-dist --no-interaction --no-progress

      - name: Static Analysis
        run: |
          make ci-analyze --keep-going

      - name: Validate composer.json
        run: |
          make composer-validate
